---
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: d0a9c8f
_src_path: ./
description: Generic project example 👤
docs: true
docsurl: https://quickplates.github.io/generic-example
projectname: generic-example
username: quickplates
