---
# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 3e277fa
_src_path: ./
description: Generic project example 👤
docs: true
docsurl: https://quickplates.github.io/generic-example
projectname: generic-example
releases: true
username: quickplates
