---
name: Lint

permissions:
  contents: read

"on":
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    env:
      NIX_CACHE_DIR: /home/runner/.nixcache
      TRUNK_CACHE_DIR: /home/runner/.trunkcache
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2
      - name: Setup Nix cache
        uses: actions/cache@v3.3.1
        id: cache-nix
        with:
          path: ${{ env.NIX_CACHE_DIR }}
          key: lint-nix
      - name: Setup Trunk cache
        uses: actions/cache@v3.3.1
        with:
          path: ${{ env.TRUNK_CACHE_DIR }}
          key: lint-trunk
      - name: Install Nix
        uses: cachix/install-nix-action@v21
        with:
          github_access_token: ${{ github.token }}
          install_url: https://releases.nixos.org/nix/nix-2.15.1/install
      - name: Import Nix store cache
        if: steps.cache-nix.outputs.cache-hit == 'true'
        run: nix-store --import < ${{ env.NIX_CACHE_DIR }}/archive.nar
      - name: Trunk Check
        uses: trunk-io/trunk-action@v1.1.1
        env:
          TRUNK_CACHE: ${{ env.TRUNK_CACHE_DIR }}
        with:
          cache: false
      - name: Export Nix store cache
        if: "!cancelled()"
        run: |
          mkdir -p ${{ env.NIX_CACHE_DIR }}
          nix-store --export $(find /nix/store -maxdepth 1 -name '*-*') \
          > ${{ env.NIX_CACHE_DIR }}/archive.nar
